### ISSUE TITLE
Issue using this with bcfg2-server 1.2.0

### ISSUE THREAD

**Issue by espro** [weiss/bcfg2-accounts#1]
Having the following issue using bcfg2-accounts on bcfg2-server 1.2.0:

``` python
Bundler: Unexpected bundler error for accounts
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/Bcfg2/Server/Plugins/Bundler.py", line 85, in BuildStructures
    bundleset.append(entries[0].get_xml_value(metadata))
  File "/usr/lib/python2.6/site-packages/Bcfg2/Server/Plugins/SGenshi.py", line 32, in get_xml_value
    data = lxml.etree.XML(stream.render('xml', strip_whitespace=False))
  File "/usr/lib64/python2.6/site-packages/genshi/core.py", line 179, in render
    return encode(generator, method=method, encoding=encoding, out=out)
  File "/usr/lib64/python2.6/site-packages/genshi/output.py", line 60, in encode
    return _encode(u''.join(list(iterator)))
  File "/usr/lib64/python2.6/site-packages/genshi/output.py", line 210, in __call__
    for kind, data, pos in stream:
  File "/usr/lib64/python2.6/site-packages/genshi/output.py", line 592, in __call__
    for kind, data, pos in stream:
  File "/usr/lib64/python2.6/site-packages/genshi/output.py", line 532, in __call__
    for ev in stream:
  File "/usr/lib64/python2.6/site-packages/genshi/core.py", line 267, in _ensure
    event = stream.next()
  File "/usr/lib64/python2.6/site-packages/genshi/core.py", line 267, in _ensure
    event = stream.next()
  File "/usr/lib/python2.6/site-packages/Bcfg2/Server/Plugins/TGenshi.py", line 31, in removecomment
    for kind, data, pos in stream:
  File "/usr/lib64/python2.6/site-packages/genshi/template/base.py", line 569, in _include
    for event in stream:
  File "/usr/lib64/python2.6/site-packages/genshi/template/markup.py", line 245, in _match
    for event in stream:
  File "/usr/lib64/python2.6/site-packages/genshi/template/base.py", line 545, in _exec
    _exec_suite(event[1], ctxt, **vars)
  File "/usr/lib64/python2.6/site-packages/genshi/template/base.py", line 302, in _exec_suite
    suite.execute(_ctxt2dict(ctxt))
  File "/usr/lib64/python2.6/site-packages/genshi/template/eval.py", line 201, in execute
    exec self.code in _globals, data
  File "/var/lib/bcfg2/Bundler/accounts.genshi", line 113, in <Suite u'from genshi.template import TemplateError ...'>
    except AttributeError: # We're running on Bcfg2 1.1.x or earlier.
AttributeError: 'ClientMetadata' object has no attribute 'Properties'
Client bcfg2.beanfield.com configuration missing bundles: accounts
```

**Comment by espro** [comment]
This was of course because I didn't have Properties enabled :)

**Comment by weiss** [comment]
> Having the following issue using bcfg2-accounts on bcfg2-server 1.2.0:
> 
> [...]
> 
> AttributeError: 'ClientMetadata' object has no attribute 'Properties'

Did you enable the "Properties" plugin in the Bcfg2 server
configuration?  (See the "Prerequisites" section in the README file.)

**Comment by weiss** [comment]
Ah, sorry, I overlooked your follow-up comment.
